### PR TITLE
Updated the Mod Class Comments

### PR DESCRIPTION
**Pull request by dtangres**
In the Mod class, the comments given for the abstract methods did not match up with the actual method names, so I thought something was up. So I fixed up the descriptions. Each description now matches up with their respective method signatures.

### CODE REVIEW

**Comment by vaughnroyko** [comment]
Hmm, not seeing this one our end. Each one matches up from. Sample:

```
        /**
         * Called when checking if a player is swimming
         * @param player The player object
         * @param isSwimming True if the player is swimming
         * @returns True if the player should be swimming, false if the player should not be swimming, or undefined to use the default logic
         */
        isPlayerSwimming(player: Player, isSwimming: boolean): boolean;
        /**
         * Called when an item is added or updated in the players inventory
         * @param item The item object
         * @param container The container object the item was added to
         */
        onAddOrUpdateInventoryItem(item: Item.IItem, container: Item.IContainer): void;
        /**
         * Called when something is built on a tile
         * @param item The item used to build the object
         * @param tile The tile something was built on
         * @param doodad The doodad that was created on the tile
         */
        onBuild(item: Item.IItem, tile: ITile, doodad: Doodad.IDoodad): void;
```

It seems your commit actually places them below each? Furthermore, the wayward.d.ts file is generated automatically from our source.

File in question: https://github.com/WaywardGame/mod-reference/blob/master/definitions/wayward.d.ts

**Comment by dtangres** [comment]
That looks odd. Lemme send you a screenshot of what I see.

**Comment by dtangres** [comment]
Oh, I see. I thought the documentation was supposed to go after the code.
I'm sorry about that.

**Comment by dtangres** [comment]
My bad, I thought the documentation was supposed to go after the method declaration, not before. I'm sorry for my nooby ways.

**Pull request closed without merging**
